Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:123456@tcp(127.0.0.1:3306)/shopping_pro?parseTime=True&loc=Local"
  DatabaseName: "shopping_pro"
  Username: "root"
  Password: "123456"


JwtSettings:
  SecretKey: "gmx"
